// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/agent_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type AgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AgentId       uint64                 `protobuf:"varint,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *AgentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentResponse) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

// Mensagem para CreateAgent
type CreateAgentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ModelId            uint32                 `protobuf:"varint,2,opt,name=modelId,proto3" json:"modelId,omitempty"`
	CompanyName        string                 `protobuf:"bytes,3,opt,name=companyName,proto3" json:"companyName,omitempty"`
	CompanyDescription string                 `protobuf:"bytes,4,opt,name=companyDescription,proto3" json:"companyDescription,omitempty"`
	BehaviourIa        string                 `protobuf:"bytes,5,opt,name=behaviourIa,proto3" json:"behaviourIa,omitempty"`
	CompanyUrl         string                 `protobuf:"bytes,6,opt,name=companyUrl,proto3" json:"companyUrl,omitempty"`
	UuidUser           string                 `protobuf:"bytes,7,opt,name=uuid_user,json=uuidUser,proto3" json:"uuid_user,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAgentRequest) GetModelId() uint32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *CreateAgentRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CreateAgentRequest) GetCompanyDescription() string {
	if x != nil {
		return x.CompanyDescription
	}
	return ""
}

func (x *CreateAgentRequest) GetBehaviourIa() string {
	if x != nil {
		return x.BehaviourIa
	}
	return ""
}

func (x *CreateAgentRequest) GetCompanyUrl() string {
	if x != nil {
		return x.CompanyUrl
	}
	return ""
}

func (x *CreateAgentRequest) GetUuidUser() string {
	if x != nil {
		return x.UuidUser
	}
	return ""
}

type CreateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAgentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAgentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Mensagem para UpdateAgent
type UpdateAgentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ModelId            uint32                 `protobuf:"varint,3,opt,name=modelId,proto3" json:"modelId,omitempty"`
	CompanyName        string                 `protobuf:"bytes,4,opt,name=companyName,proto3" json:"companyName,omitempty"`
	CompanyDescription string                 `protobuf:"bytes,5,opt,name=companyDescription,proto3" json:"companyDescription,omitempty"`
	BehaviourIa        string                 `protobuf:"bytes,6,opt,name=behaviourIa,proto3" json:"behaviourIa,omitempty"`
	CompanyUrl         string                 `protobuf:"bytes,7,opt,name=companyUrl,proto3" json:"companyUrl,omitempty"`
	UuidUser           string                 `protobuf:"bytes,8,opt,name=uuid_user,json=uuidUser,proto3" json:"uuid_user,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAgentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAgentRequest) GetModelId() uint32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *UpdateAgentRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *UpdateAgentRequest) GetCompanyDescription() string {
	if x != nil {
		return x.CompanyDescription
	}
	return ""
}

func (x *UpdateAgentRequest) GetBehaviourIa() string {
	if x != nil {
		return x.BehaviourIa
	}
	return ""
}

func (x *UpdateAgentRequest) GetCompanyUrl() string {
	if x != nil {
		return x.CompanyUrl
	}
	return ""
}

func (x *UpdateAgentRequest) GetUuidUser() string {
	if x != nil {
		return x.UuidUser
	}
	return ""
}

type UpdateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentResponse) Reset() {
	*x = UpdateAgentResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentResponse) ProtoMessage() {}

func (x *UpdateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAgentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Mensagem para GetAgent
type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UuidUser      string                 `protobuf:"bytes,2,opt,name=uuid_user,json=uuidUser,proto3" json:"uuid_user,omitempty"`
	Instructions  bool                   `protobuf:"varint,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAgentRequest) GetUuidUser() string {
	if x != nil {
		return x.UuidUser
	}
	return ""
}

func (x *GetAgentRequest) GetInstructions() bool {
	if x != nil {
		return x.Instructions
	}
	return false
}

type Agent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ModelId            uint32                 `protobuf:"varint,3,opt,name=modelId,proto3" json:"modelId,omitempty"`
	CompanyName        string                 `protobuf:"bytes,4,opt,name=companyName,proto3" json:"companyName,omitempty"`
	CompanyDescription string                 `protobuf:"bytes,5,opt,name=companyDescription,proto3" json:"companyDescription,omitempty"`
	BehaviourIa        string                 `protobuf:"bytes,6,opt,name=behaviourIa,proto3" json:"behaviourIa,omitempty"`
	CompanyUrl         string                 `protobuf:"bytes,7,opt,name=companyUrl,proto3" json:"companyUrl,omitempty"`
	UuidUser           string                 `protobuf:"bytes,8,opt,name=uuid_user,json=uuidUser,proto3" json:"uuid_user,omitempty"`
	Instructions       string                 `protobuf:"bytes,9,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_proto_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *Agent) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetModelId() uint32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *Agent) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Agent) GetCompanyDescription() string {
	if x != nil {
		return x.CompanyDescription
	}
	return ""
}

func (x *Agent) GetBehaviourIa() string {
	if x != nil {
		return x.BehaviourIa
	}
	return ""
}

func (x *Agent) GetCompanyUrl() string {
	if x != nil {
		return x.CompanyUrl
	}
	return ""
}

func (x *Agent) GetUuidUser() string {
	if x != nil {
		return x.UuidUser
	}
	return ""
}

func (x *Agent) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// Mensagem para ListAgents
type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidUser      string                 `protobuf:"bytes,1,opt,name=uuid_user,json=uuidUser,proto3" json:"uuid_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListAgentsRequest) GetUuidUser() string {
	if x != nil {
		return x.UuidUser
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

// Mensagem para DeleteAgent
type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UuidUser      string                 `protobuf:"bytes,2,opt,name=uuid_user,json=uuidUser,proto3" json:"uuid_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteAgentRequest) GetUuidUser() string {
	if x != nil {
		return x.UuidUser
	}
	return ""
}

type DeleteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAgentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_agent_service_proto protoreflect.FileDescriptor

const file_proto_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/agent_service.proto\x12\x05agent\"0\n" +
	"\fAgentRequest\x12 \n" +
	"\vphoneNumber\x18\x01 \x01(\tR\vphoneNumber\"A\n" +
	"\rAgentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aagentId\x18\x02 \x01(\x04R\aagentId\"\xf3\x01\n" +
	"\x12CreateAgentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amodelId\x18\x02 \x01(\rR\amodelId\x12 \n" +
	"\vcompanyName\x18\x03 \x01(\tR\vcompanyName\x12.\n" +
	"\x12companyDescription\x18\x04 \x01(\tR\x12companyDescription\x12 \n" +
	"\vbehaviourIa\x18\x05 \x01(\tR\vbehaviourIa\x12\x1e\n" +
	"\n" +
	"companyUrl\x18\x06 \x01(\tR\n" +
	"companyUrl\x12\x1b\n" +
	"\tuuid_user\x18\a \x01(\tR\buuidUser\"=\n" +
	"\x13CreateAgentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x83\x02\n" +
	"\x12UpdateAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amodelId\x18\x03 \x01(\rR\amodelId\x12 \n" +
	"\vcompanyName\x18\x04 \x01(\tR\vcompanyName\x12.\n" +
	"\x12companyDescription\x18\x05 \x01(\tR\x12companyDescription\x12 \n" +
	"\vbehaviourIa\x18\x06 \x01(\tR\vbehaviourIa\x12\x1e\n" +
	"\n" +
	"companyUrl\x18\a \x01(\tR\n" +
	"companyUrl\x12\x1b\n" +
	"\tuuid_user\x18\b \x01(\tR\buuidUser\"-\n" +
	"\x13UpdateAgentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"b\n" +
	"\x0fGetAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tuuid_user\x18\x02 \x01(\tR\buuidUser\x12\"\n" +
	"\finstructions\x18\x03 \x01(\bR\finstructions\"\x9a\x02\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amodelId\x18\x03 \x01(\rR\amodelId\x12 \n" +
	"\vcompanyName\x18\x04 \x01(\tR\vcompanyName\x12.\n" +
	"\x12companyDescription\x18\x05 \x01(\tR\x12companyDescription\x12 \n" +
	"\vbehaviourIa\x18\x06 \x01(\tR\vbehaviourIa\x12\x1e\n" +
	"\n" +
	"companyUrl\x18\a \x01(\tR\n" +
	"companyUrl\x12\x1b\n" +
	"\tuuid_user\x18\b \x01(\tR\buuidUser\x12\"\n" +
	"\finstructions\x18\t \x01(\tR\finstructions\"6\n" +
	"\x10GetAgentResponse\x12\"\n" +
	"\x05agent\x18\x01 \x01(\v2\f.agent.AgentR\x05agent\"0\n" +
	"\x11ListAgentsRequest\x12\x1b\n" +
	"\tuuid_user\x18\x01 \x01(\tR\buuidUser\":\n" +
	"\x12ListAgentsResponse\x12$\n" +
	"\x06agents\x18\x01 \x03(\v2\f.agent.AgentR\x06agents\"A\n" +
	"\x12DeleteAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tuuid_user\x18\x02 \x01(\tR\buuidUser\"-\n" +
	"\x13DeleteAgentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xa5\x03\n" +
	"\x0eAIAgentService\x12D\n" +
	"\vCreateAgent\x12\x19.agent.CreateAgentRequest\x1a\x1a.agent.CreateAgentResponse\x12D\n" +
	"\vUpdateAgent\x12\x19.agent.UpdateAgentRequest\x1a\x1a.agent.UpdateAgentResponse\x12;\n" +
	"\bGetAgent\x12\x16.agent.GetAgentRequest\x1a\x17.agent.GetAgentResponse\x12A\n" +
	"\n" +
	"ListAgents\x12\x18.agent.ListAgentsRequest\x1a\x19.agent.ListAgentsResponse\x12D\n" +
	"\vDeleteAgent\x12\x19.agent.DeleteAgentRequest\x1a\x1a.agent.DeleteAgentResponse\x12A\n" +
	"\x14GetAgentModelByPhone\x12\x13.agent.AgentRequest\x1a\x14.agent.AgentResponseB\x13Z\x11seu-projeto/protob\x06proto3"

var (
	file_proto_agent_service_proto_rawDescOnce sync.Once
	file_proto_agent_service_proto_rawDescData []byte
)

func file_proto_agent_service_proto_rawDescGZIP() []byte {
	file_proto_agent_service_proto_rawDescOnce.Do(func() {
		file_proto_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_service_proto_rawDesc), len(file_proto_agent_service_proto_rawDesc)))
	})
	return file_proto_agent_service_proto_rawDescData
}

var file_proto_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_agent_service_proto_goTypes = []any{
	(*AgentRequest)(nil),        // 0: agent.AgentRequest
	(*AgentResponse)(nil),       // 1: agent.AgentResponse
	(*CreateAgentRequest)(nil),  // 2: agent.CreateAgentRequest
	(*CreateAgentResponse)(nil), // 3: agent.CreateAgentResponse
	(*UpdateAgentRequest)(nil),  // 4: agent.UpdateAgentRequest
	(*UpdateAgentResponse)(nil), // 5: agent.UpdateAgentResponse
	(*GetAgentRequest)(nil),     // 6: agent.GetAgentRequest
	(*Agent)(nil),               // 7: agent.Agent
	(*GetAgentResponse)(nil),    // 8: agent.GetAgentResponse
	(*ListAgentsRequest)(nil),   // 9: agent.ListAgentsRequest
	(*ListAgentsResponse)(nil),  // 10: agent.ListAgentsResponse
	(*DeleteAgentRequest)(nil),  // 11: agent.DeleteAgentRequest
	(*DeleteAgentResponse)(nil), // 12: agent.DeleteAgentResponse
}
var file_proto_agent_service_proto_depIdxs = []int32{
	7,  // 0: agent.GetAgentResponse.agent:type_name -> agent.Agent
	7,  // 1: agent.ListAgentsResponse.agents:type_name -> agent.Agent
	2,  // 2: agent.AIAgentService.CreateAgent:input_type -> agent.CreateAgentRequest
	4,  // 3: agent.AIAgentService.UpdateAgent:input_type -> agent.UpdateAgentRequest
	6,  // 4: agent.AIAgentService.GetAgent:input_type -> agent.GetAgentRequest
	9,  // 5: agent.AIAgentService.ListAgents:input_type -> agent.ListAgentsRequest
	11, // 6: agent.AIAgentService.DeleteAgent:input_type -> agent.DeleteAgentRequest
	0,  // 7: agent.AIAgentService.GetAgentModelByPhone:input_type -> agent.AgentRequest
	3,  // 8: agent.AIAgentService.CreateAgent:output_type -> agent.CreateAgentResponse
	5,  // 9: agent.AIAgentService.UpdateAgent:output_type -> agent.UpdateAgentResponse
	8,  // 10: agent.AIAgentService.GetAgent:output_type -> agent.GetAgentResponse
	10, // 11: agent.AIAgentService.ListAgents:output_type -> agent.ListAgentsResponse
	12, // 12: agent.AIAgentService.DeleteAgent:output_type -> agent.DeleteAgentResponse
	1,  // 13: agent.AIAgentService.GetAgentModelByPhone:output_type -> agent.AgentResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_agent_service_proto_init() }
func file_proto_agent_service_proto_init() {
	if File_proto_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_service_proto_rawDesc), len(file_proto_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_service_proto_goTypes,
		DependencyIndexes: file_proto_agent_service_proto_depIdxs,
		MessageInfos:      file_proto_agent_service_proto_msgTypes,
	}.Build()
	File_proto_agent_service_proto = out.File
	file_proto_agent_service_proto_goTypes = nil
	file_proto_agent_service_proto_depIdxs = nil
}
