// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/processor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessWebhookRequest) Reset() {
	*x = ProcessWebhookRequest{}
	mi := &file_proto_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessWebhookRequest) ProtoMessage() {}

func (x *ProcessWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessWebhookRequest.ProtoReflect.Descriptor instead.
func (*ProcessWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessWebhookRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ProcessWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessWebhookResponse) Reset() {
	*x = ProcessWebhookResponse{}
	mi := &file_proto_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessWebhookResponse) ProtoMessage() {}

func (x *ProcessWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessWebhookResponse.ProtoReflect.Descriptor instead.
func (*ProcessWebhookResponse) Descriptor() ([]byte, []int) {
	return file_proto_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessWebhookResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_processor_proto protoreflect.FileDescriptor

const file_proto_processor_proto_rawDesc = "" +
	"\n" +
	"\x15proto/processor.proto\x12\tprocessor\"A\n" +
	"\x15ProcessWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"J\n" +
	"\x16ProcessWebhookResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2p\n" +
	"\x17WebhookProcessorService\x12U\n" +
	"\x0eProcessWebhook\x12 .processor.ProcessWebhookRequest\x1a!.processor.ProcessWebhookResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_processor_proto_rawDescOnce sync.Once
	file_proto_processor_proto_rawDescData []byte
)

func file_proto_processor_proto_rawDescGZIP() []byte {
	file_proto_processor_proto_rawDescOnce.Do(func() {
		file_proto_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_processor_proto_rawDesc), len(file_proto_processor_proto_rawDesc)))
	})
	return file_proto_processor_proto_rawDescData
}

var file_proto_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_processor_proto_goTypes = []any{
	(*ProcessWebhookRequest)(nil),  // 0: processor.ProcessWebhookRequest
	(*ProcessWebhookResponse)(nil), // 1: processor.ProcessWebhookResponse
}
var file_proto_processor_proto_depIdxs = []int32{
	0, // 0: processor.WebhookProcessorService.ProcessWebhook:input_type -> processor.ProcessWebhookRequest
	1, // 1: processor.WebhookProcessorService.ProcessWebhook:output_type -> processor.ProcessWebhookResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_processor_proto_init() }
func file_proto_processor_proto_init() {
	if File_proto_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_processor_proto_rawDesc), len(file_proto_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_processor_proto_goTypes,
		DependencyIndexes: file_proto_processor_proto_depIdxs,
		MessageInfos:      file_proto_processor_proto_msgTypes,
	}.Build()
	File_proto_processor_proto = out.File
	file_proto_processor_proto_goTypes = nil
	file_proto_processor_proto_depIdxs = nil
}
