// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/processor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookProcessorService_ProcessWebhook_FullMethodName = "/processor.WebhookProcessorService/ProcessWebhook"
)

// WebhookProcessorServiceClient is the client API for WebhookProcessorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebhookProcessorServiceClient interface {
	ProcessWebhook(ctx context.Context, in *ProcessWebhookRequest, opts ...grpc.CallOption) (*ProcessWebhookResponse, error)
}

type webhookProcessorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookProcessorServiceClient(cc grpc.ClientConnInterface) WebhookProcessorServiceClient {
	return &webhookProcessorServiceClient{cc}
}

func (c *webhookProcessorServiceClient) ProcessWebhook(ctx context.Context, in *ProcessWebhookRequest, opts ...grpc.CallOption) (*ProcessWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookProcessorService_ProcessWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookProcessorServiceServer is the server API for WebhookProcessorService service.
// All implementations must embed UnimplementedWebhookProcessorServiceServer
// for forward compatibility.
type WebhookProcessorServiceServer interface {
	ProcessWebhook(context.Context, *ProcessWebhookRequest) (*ProcessWebhookResponse, error)
	mustEmbedUnimplementedWebhookProcessorServiceServer()
}

// UnimplementedWebhookProcessorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookProcessorServiceServer struct{}

func (UnimplementedWebhookProcessorServiceServer) ProcessWebhook(context.Context, *ProcessWebhookRequest) (*ProcessWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessWebhook not implemented")
}
func (UnimplementedWebhookProcessorServiceServer) mustEmbedUnimplementedWebhookProcessorServiceServer() {
}
func (UnimplementedWebhookProcessorServiceServer) testEmbeddedByValue() {}

// UnsafeWebhookProcessorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookProcessorServiceServer will
// result in compilation errors.
type UnsafeWebhookProcessorServiceServer interface {
	mustEmbedUnimplementedWebhookProcessorServiceServer()
}

func RegisterWebhookProcessorServiceServer(s grpc.ServiceRegistrar, srv WebhookProcessorServiceServer) {
	// If the following call pancis, it indicates UnimplementedWebhookProcessorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookProcessorService_ServiceDesc, srv)
}

func _WebhookProcessorService_ProcessWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookProcessorServiceServer).ProcessWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookProcessorService_ProcessWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookProcessorServiceServer).ProcessWebhook(ctx, req.(*ProcessWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookProcessorService_ServiceDesc is the grpc.ServiceDesc for WebhookProcessorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookProcessorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "processor.WebhookProcessorService",
	HandlerType: (*WebhookProcessorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessWebhook",
			Handler:    _WebhookProcessorService_ProcessWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/processor.proto",
}
