package model

// Main struct to hold the entire JSON payload
type WWEBJSPayload struct {
	Data struct {
		ID struct {
			FromMe     bool   `json:"fromMe,omitempty"`
			Remote     string `json:"remote,omitempty"`
			ID         string `json:"id,omitempty"`
			Serialized string `json:"_serialized,omitempty"`
		} `json:"id,omitempty"`
		Viewed                      bool     `json:"viewed,omitempty"`
		Body                        string   `json:"body,omitempty"`
		Type                        string   `json:"type,omitempty"`
		T                           int64    `json:"t,omitempty"`
		ClientReceivedTsMillis      int64    `json:"clientReceivedTsMillis,omitempty"`
		NotifyName                  string   `json:"notifyName,omitempty"`
		From                        string   `json:"from,omitempty"`
		To                          string   `json:"to,omitempty"`
		Ack                         int      `json:"ack,omitempty"`
		Invis                       bool     `json:"invis,omitempty"`
		IsNewMsg                    bool     `json:"isNewMsg,omitempty"`
		Star                        bool     `json:"star,omitempty"`
		KicNotified                 bool     `json:"kicNotified,omitempty"`
		RecvFresh                   bool     `json:"recvFresh,omitempty"`
		IsFromTemplate              bool     `json:"isFromTemplate,omitempty"`
		PollInvalidated             bool     `json:"pollInvalidated,omitempty"`
		IsSentCagPollCreation       bool     `json:"isSentCagPollCreation,omitempty"`
		LatestEditMsgKey            *string  `json:"latestEditMsgKey,omitempty"`
		LatestEditSenderTimestampMs *int64   `json:"latestEditSenderTimestampMs,omitempty"`
		MentionedJidList            []string `json:"mentionedJidList,omitempty"`
		GroupMentions               []string `json:"groupMentions,omitempty"`
		IsEventCanceled             bool     `json:"isEventCanceled,omitempty"`
		EventInvalidated            bool     `json:"eventInvalidated,omitempty"`
		IsVcardOverMmsDocument      bool     `json:"isVcardOverMmsDocument,omitempty"`
		IsForwarded                 bool     `json:"isForwarded,omitempty"`
		IsQuestion                  bool     `json:"isQuestion,omitempty"`
		QuestionReplyQuotedMessage  *string  `json:"questionReplyQuotedMessage,omitempty"`
		QuestionResponsesCount      int      `json:"questionResponsesCount,omitempty"`
		ReadQuestionResponsesCount  int      `json:"readQuestionResponsesCount,omitempty"`
		HasReaction                 bool     `json:"hasReaction,omitempty"`
		ViewMode                    string   `json:"viewMode,omitempty"`
		// MessageSecret                []int    `json:"messageSecret"`
		ProductHeaderImageRejected   bool    `json:"productHeaderImageRejected,omitempty"`
		LastPlaybackProgress         int     `json:"lastPlaybackProgress,omitempty"`
		IsDynamicReplyButtonsMsg     bool    `json:"isDynamicReplyButtonsMsg,omitempty"`
		IsCarouselCard               bool    `json:"isCarouselCard,omitempty"`
		ParentMsgId                  *string `json:"parentMsgId,omitempty"`
		CallSilenceReason            *string `json:"callSilenceReason,omitempty"`
		IsVideoCall                  bool    `json:"isVideoCall,omitempty"`
		CallDuration                 *string `json:"callDuration,omitempty"`
		CallCreator                  *string `json:"callCreator,omitempty"`
		CallParticipants             *string `json:"callParticipants,omitempty"`
		IsCallLink                   *string `json:"isCallLink,omitempty"`
		CallLinkToken                *string `json:"callLinkToken,omitempty"`
		IsMdHistoryMsg               bool    `json:"isMdHistoryMsg,omitempty"`
		StickerSentTs                int     `json:"stickerSentTs,omitempty"`
		IsAvatar                     bool    `json:"isAvatar,omitempty"`
		LastUpdateFromServerTs       int     `json:"lastUpdateFromServerTs,omitempty"`
		InvokedBotWid                *string `json:"invokedBotWid,omitempty"`
		BizBotType                   *string `json:"bizBotType,omitempty"`
		BotResponseTargetId          *string `json:"botResponseTargetId,omitempty"`
		BotPluginType                *string `json:"botPluginType,omitempty"`
		BotPluginReferenceIndex      *string `json:"botPluginReferenceIndex,omitempty"`
		BotPluginSearchProvider      *string `json:"botPluginSearchProvider,omitempty"`
		BotPluginSearchUrl           *string `json:"botPluginSearchUrl,omitempty"`
		BotPluginSearchQuery         *string `json:"botPluginSearchQuery,omitempty"`
		BotPluginMaybeParent         bool    `json:"botPluginMaybeParent,omitempty"`
		BotReelPluginThumbnailCdnUrl *string `json:"botReelPluginThumbnailCdnUrl,omitempty"`
		BotMessageDisclaimerText     *string `json:"botMessageDisclaimerText,omitempty"`
		BotMsgBodyType               *string `json:"botMsgBodyType,omitempty"`
		DeprecatedMms3Url            string  `json:"deprecatedMms3Url,omitempty"`
		ReportingTokenInfo           struct {
			ReportingToken interface{} `json:"reportingToken,omitempty"`
			Version        interface{} `json:"version,omitempty"`
			ReportingTag   interface{} `json:"reportingTag,omitempty"`
		} `json:"reportingTokenInfo,omitempty"`
		RequiresDirectConnection              *string  `json:"requiresDirectConnection,omitempty"`
		BizContentPlaceholderType             *string  `json:"bizContentPlaceholderType,omitempty"`
		HostedBizEncStateMismatch             bool     `json:"hostedBizEncStateMismatch,omitempty"`
		SenderOrRecipientAccountTypeHosted    bool     `json:"senderOrRecipientAccountTypeHosted,omitempty"`
		PlaceholderCreatedWhenAccountIsHosted bool     `json:"placeholderCreatedWhenAccountIsHosted,omitempty"`
		GalaxyFlowDisabled                    bool     `json:"galaxyFlowDisabled,omitempty"`
		Links                                 []string `json:"links,omitempty"`
	} `json:"_data,omitempty"`
	ID struct {
		FromMe     bool   `json:"fromMe,omitempty"`
		Remote     string `json:"remote,omitempty"`
		ID         string `json:"id,omitempty"`
		Serialized string `json:"_serialized,omitempty"`
	} `json:"id,omitempty"`
	Ack             int      `json:"ack,omitempty"`
	HasMedia        bool     `json:"hasMedia,omitempty"`
	Body            string   `json:"body,omitempty"`
	Type            string   `json:"type,omitempty"`
	Timestamp       int64    `json:"timestamp,omitempty"`
	From            string   `json:"from,omitempty"`
	To              string   `json:"to,omitempty"`
	DeviceType      string   `json:"deviceType,omitempty"`
	IsForwarded     bool     `json:"isForwarded,omitempty"`
	ForwardingScore int      `json:"forwardingScore,omitempty"`
	IsStatus        bool     `json:"isStatus,omitempty"`
	IsStarred       bool     `json:"isStarred,omitempty"`
	FromMe          bool     `json:"fromMe,omitempty"`
	HasQuotedMsg    bool     `json:"hasQuotedMsg,omitempty"`
	HasReaction     bool     `json:"hasReaction,omitempty"`
	VCards          []string `json:"vCards,omitempty"`
	MentionedIds    []string `json:"mentionedIds,omitempty"`
	GroupMentions   []string `json:"groupMentions,omitempty"`
	IsGif           bool     `json:"isGif,omitempty"`
	Links           []string `json:"links,omitempty"`
}
